const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {spawnSync}=require('node:child_process');
const {SessionStore,codexEvent}=require('../src/state.cjs');const {Watcher}=require('../src/watcher.cjs');const {normalize}=require('../scripts/bridge.cjs');const {install}=require('../src/integrations.cjs');
const now=Date.now();const event=(session,state,at=now)=>({provider:'codex',session,project:'Agentibou',state,at});
function temp(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'agentibou-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir;}
test('one completed session celebrates, then resumes remaining work',()=>{const s=new SessionStore();s.accept(event('one','thinking'),now);s.accept(event('two','thinking'),now);s.accept(event('one','done',now+10),now+10);assert.equal(s.snapshot(now+11).state,'done');assert.equal(s.snapshot(now+8000).state,'thinking');assert.equal(s.snapshot(now+8000).active,1);});
test('out-of-order events cannot resurrect completed work',()=>{const s=new SessionStore();s.accept(event('a','done'),now);assert.equal(s.accept(event('a','thinking',now-1000),now),false);assert.equal(s.snapshot(now+8000).state,'idle');});
test('stale working sessions never report success; errors stay visible',()=>{const s=new SessionStore();s.accept(event('a','thinking'),now);assert.equal(s.snapshot(now+1200001).state,'idle');assert.equal(s.snapshot(now+1200001).sessions[0].stale,true);s.accept(event('a','error',now+1200002),now+1200002);assert.equal(s.snapshot(now+1200003).state,'idle');});
test('invalid and future events are rejected; old sessions expire',()=>{const s=new SessionStore();assert.equal(s.accept({...event('x','idle'),provider:'unknown'},now),false);assert.equal(s.accept(event('x','done',now+120000),now),false);s.accept(event('a','idle'),now);assert.equal(s.snapshot(now+86400001).sessions.length,0);});
test('bridge strips private payloads and supports both hook ID formats',()=>{for(const input of [{session_id:'abc'},{sessionId:'abc'}]){const e=normalize('claude','thinking',{...input,cwd:'/tmp/project',prompt:'SECRET',tool_input:{command:'SECRET'},transcript_path:'SECRET'});assert.equal(e.session,'abc');assert.equal(e.project,'project');assert.ok(!JSON.stringify(e).includes('SECRET'));}});
test('Codex only interprets lifecycle/progress, not a final text heuristic',()=>{const meta={};const line=(type,payload)=>JSON.stringify({timestamp:new Date(now).toISOString(),type,payload});codexEvent(line('session_meta',{id:'abc',cwd:'/tmp/test'}),meta);assert.equal(codexEvent(line('event_msg',{type:'task_started'}),meta).state,'thinking');assert.equal(codexEvent(line('response_item',{role:'assistant',phase:'final'}),meta),null);assert.equal(codexEvent(line('event_msg',{type:'task_complete'}),meta).state,'done');assert.equal(codexEvent(line('event_msg',{type:'token_count'}),meta),null);assert.equal(codexEvent(line('event_msg',{type:'turn_aborted'}),meta).state,'idle');});
test('watcher handles incremental and split JSON, truncation and simultaneous providers',t=>{const root=temp(t),s=new SessionStore();const d=new Date(),dir=path.join(root,'codex','sessions',String(d.getFullYear()),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0'));fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,'rollout-test.jsonl');const meta=JSON.stringify({type:'session_meta',payload:{id:'s',cwd:'/tmp/Agentibou'}})+'\n';const line=JSON.stringify({timestamp:new Date(now).toISOString(),type:'event_msg',payload:{type:'task_started'}})+'\n';fs.writeFileSync(file,meta+line.slice(0,35));const w=new Watcher(s,root,path.join(root,'codex'));w.poll();assert.equal(s.snapshot().state,'idle');fs.appendFileSync(file,line.slice(35));w.poll();assert.equal(s.snapshot().state,'thinking');fs.writeFileSync(file,meta);w.poll();fs.appendFileSync(file,JSON.stringify({timestamp:new Date(now+1).toISOString(),type:'event_msg',payload:{type:'task_complete'}})+'\n');w.poll();assert.equal(s.snapshot(now+2).state,'done');});
test('hook executable persists metadata only and always allows malformed input',t=>{const root=temp(t),bridge=path.resolve('scripts/bridge.cjs');const good=spawnSync(process.execPath,[bridge,'claude','thinking'],{input:JSON.stringify({session_id:'test',cwd:'/tmp/example',prompt:'TOP_SECRET'}),env:{...process.env,AGENTIBOU_HOME:root}});assert.equal(good.status,0);assert.equal(good.stdout.toString(),'');const files=fs.readdirSync(path.join(root,'events'));assert.equal(files.length,1);assert.ok(!fs.readFileSync(path.join(root,'events',files[0]),'utf8').includes('TOP_SECRET'));const bad=spawnSync(process.execPath,[bridge,'claude','done'],{input:'invalid',env:{...process.env,AGENTIBOU_HOME:root}});assert.equal(bad.status,0);});
test('Claude installer preserves unrelated settings/hooks and is idempotent',t=>{const home=temp(t),file=path.join(home,'.claude','settings.json');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify({model:'existing',hooks:{Stop:[{matcher:'',hooks:[{type:'command',command:'echo original'}]}]}}));const opts={home,root:path.join(home,'.agentibou'),exe:process.execPath,bridge:path.resolve('scripts/bridge.cjs')};install('claude',opts);install('claude',opts);const d=JSON.parse(fs.readFileSync(file));assert.equal(d.model,'existing');assert.equal(d.hooks.Stop.length,2);assert.equal(d.hooks.Stop[0].hooks[0].command,'echo original');assert.equal(d.hooks.Stop[1].hooks.length,1);assert.ok(fs.readdirSync(path.dirname(file)).some(n=>n.includes('backup')));});
test('malformed configuration is never overwritten',t=>{const home=temp(t),file=path.join(home,'.claude','settings.json');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,'{ broken');assert.throws(()=>install('claude',{home,root:path.join(home,'.agentibou'),exe:process.execPath,bridge:path.resolve('scripts/bridge.cjs')}));assert.equal(fs.readFileSync(file,'utf8'),'{ broken');});
test('VS Code hooks and Visual Studio MCP are separate and preserve existing servers',t=>{const home=temp(t),opts={home,root:path.join(home,'.agentibou'),project:home,exe:process.execPath,bridge:path.resolve('scripts/bridge.cjs')};const vs=install('vscode',opts);const d=JSON.parse(fs.readFileSync(vs.file));assert.ok(d.hooks.UserPromptSubmit);assert.ok(d.hooks.Stop);const mcp=path.join(home,'.vs','mcp.json');fs.mkdirSync(path.dirname(mcp),{recursive:true});fs.writeFileSync(mcp,JSON.stringify({servers:{existing:{url:'https://example.com'}}}));install('visualstudio',opts);const m=JSON.parse(fs.readFileSync(mcp));assert.ok(m.servers.existing);assert.ok(m.servers.agentibou);});
test('MCP stdio handshake, discovery, notification, and state update',t=>{const root=temp(t);const msgs=[{jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2024-11-05'}},{jsonrpc:'2.0',method:'notifications/initialized'},{jsonrpc:'2.0',id:2,method:'tools/list'},{jsonrpc:'2.0',id:3,method:'tools/call',params:{name:'agentibou_state',arguments:{state:'thinking'}}}];const r=spawnSync(process.execPath,[path.resolve('scripts/bridge.cjs'),'mcp'],{input:msgs.map(m=>JSON.stringify(m)).join('\n')+'\n',env:{...process.env,AGENTIBOU_HOME:root}});assert.equal(r.status,0);const lines=r.stdout.toString().trim().split('\n').map(JSON.parse);assert.equal(lines.length,3);assert.equal(lines[1].result.tools[0].name,'agentibou_state');assert.ok(!lines[2].result.isError);const e=JSON.parse(fs.readFileSync(path.join(root,'events',fs.readdirSync(path.join(root,'events'))[0])));assert.equal(e.provider,'visualstudio');assert.equal(e.state,'thinking');});
test('generated shell hook handles spaces and apostrophes without interpreting path content',{skip:process.platform==='win32'},t=>{const base=temp(t);const home=path.join(base,"Matt's $workspace `literal`");fs.mkdirSync(home);const root=path.join(home,'.agentibou');const result=install('claude',{home,root,exe:process.execPath,bridge:path.resolve('scripts/bridge.cjs')});const d=JSON.parse(fs.readFileSync(result.file));const command=d.hooks.UserPromptSubmit[0].hooks[0].command;const r=spawnSync('/bin/sh',['-c',command],{input:JSON.stringify({session_id:'quoted-path',cwd:home}),env:{...process.env,AGENTIBOU_HOME:root}});assert.equal(r.status,0);const event=JSON.parse(fs.readFileSync(path.join(root,'events',fs.readdirSync(path.join(root,'events'))[0])));assert.equal(event.session,'quoted-path');assert.equal(event.state,'thinking');});
test('completion remains clickable after celebration; opening acknowledges only the selected completion',()=>{const s=new SessionStore();s.accept(event('one','done'),now);s.accept(event('two','done',now+1),now+1);assert.equal(s.snapshot(now+9000).completion.session,'two');s.acknowledge('codex:two',now);assert.equal(s.snapshot(now+9000).completion.session,'two');s.acknowledge('codex:two',now+1);assert.equal(s.snapshot(now+9000).completion.session,'one');});
test('resuming invalidates the old completion; session end preserves its return link',()=>{const s=new SessionStore();s.accept(event('one','done'),now);s.accept(event('one','idle',now+1),now+1);assert.equal(s.snapshot(now+2).completion.session,'one');s.accept(event('one','thinking',now+3),now+3);assert.equal(s.snapshot(now+4).completion,null);s.accept(event('one','done',now+5),now+5);assert.equal(s.snapshot(now+86400006).completion,null);});
test('working is active, with the same stale-signal protection as reasoning',()=>{const s=new SessionStore();s.accept(event('one','working'),now);assert.equal(s.snapshot(now+1).active,1);assert.equal(s.snapshot(now+1).state,'working');assert.equal(s.snapshot(now+1200001).state,'idle');});
test('Codex tool execution and reasoning use different visual states',()=>{const meta={session:'one',project:'test'};const line=(type,payload)=>JSON.stringify({timestamp:new Date(now).toISOString(),type,payload});assert.equal(codexEvent(line('response_item',{type:'function_call'}),meta).state,'working');assert.equal(codexEvent(line('event_msg',{type:'token_count'}),meta).state,'working');assert.equal(codexEvent(line('event_msg',{type:'item_completed',item:{type:'CommandExecution'}}),meta).state,'thinking');assert.equal(codexEvent(line('event_msg',{type:'item_completed',item:{type:'Reasoning'}}),meta).state,'thinking');});
test('conversation destinations are generated from validated metadata, never arbitrary URLs',()=>{const {destination}=require('../src/navigation.cjs');const id='01a09630-c63a-7cb2-b36a-42be68437b18';assert.equal(destination({provider:'codex',session:id}).url,'codex://threads/'+id);assert.equal(destination({provider:'codex',session:'new?prompt=evil'}).kind,'unavailable');assert.equal(destination({provider:'unknown',session:id,cwd:'javascript:evil'}).kind,'unavailable');assert.equal(destination({provider:'copilot',cwd:'C:\\Matt #1\\project'}).url,'vscode://file/C:/Matt%20%231/project');assert.equal(destination({provider:'copilot',cwd:'/tmp/test?x=#'}).url,'vscode://file//tmp/test%3Fx%3D%23');assert.equal(destination({provider:'claude',session:id}).url,'claude://resume?session='+id);assert.equal(destination({provider:'claude',session:'x; rm'}).kind,'unavailable');});


test('companion library preserves image bytes and selections across restarts',t=>{
 const {CompanionLibrary,cleanSelection,selectedCompanion}=require('../src/companions.cjs');const root=temp(t),builtin=path.resolve('src/assets/vic.webp'),bytes=fs.readFileSync(builtin);const lib=new CompanionLibrary(root,builtin);const added=lib.add('Pixel',bytes,'webp');const restored=new CompanionLibrary(root,builtin);assert.equal(restored.list()[1].name,'Paprika');assert.equal(restored.list()[1].builtin,true);assert.equal(restored.list().find(p=>p.id===added.id).name,'Pixel');assert.deepEqual(fs.readFileSync(require('node:url').fileURLToPath(added.imageUrl)),bytes);
 const s={mode:'per-tool',defaultId:'vic',assignments:{claude:added.id,copilot:added.id,unknown:added.id}};assert.equal(selectedCompanion(s,restored.list(),'claude').id,added.id);assert.equal(selectedCompanion(s,restored.list(),'codex').id,'vic');assert.equal(selectedCompanion(s,restored.list(),null).id,'vic');assert.equal(selectedCompanion({...s,mode:'shared'},restored.list(),'claude').id,'vic');assert.equal(cleanSelection(s,restored.list()).assignments.unknown,undefined);
 fs.rmSync(require('node:url').fileURLToPath(added.imageUrl));assert.equal(selectedCompanion(s,new CompanionLibrary(root,builtin).list(),'claude').id,'vic');
});
test('companion import rejects invalid formats and names',()=>{const {imageType,cleanName}=require('../src/companions.cjs');assert.throws(()=>imageType(Buffer.from('<svg></svg>')));assert.throws(()=>imageType(Buffer.alloc(21*1024*1024)));assert.throws(()=>cleanName('  '));assert.throws(()=>cleanName('x'.repeat(41)));});
test('Claude Desktop maps hook IDs to exact desktop sessions without reading transcripts',t=>{
 const {findDesktopSession}=require('../src/claude-desktop.cjs'),{destination}=require('../src/navigation.cjs');const root=temp(t),dir=path.join(root,'claude-code-sessions','account','org');fs.mkdirSync(dir,{recursive:true});const cli='01a09630-c63a-7cb2-b36a-42be68437b18',local='local_12345678-1234-1234-1234-123456789abc';fs.writeFileSync(path.join(dir,local+'.json'),JSON.stringify({sessionId:local,cliSessionId:cli,isArchived:true}));fs.writeFileSync(path.join(dir,'local_broken.json'),'{');assert.equal(findDesktopSession(root,cli),local);assert.equal(findDesktopSession(root,'other'),undefined);assert.equal(destination({provider:'claude',session:cli},{claudeDesktopId:findDesktopSession(root,cli)}).url,'claude://claude.ai/claude-code-desktop/'+local);assert.equal(destination({provider:'claude',session:local}).exact,true);assert.equal(destination({provider:'claude',session:'local_x?prompt=evil'}).kind,'unavailable');
});

test('animation priority is celebration, working, thinking, neutral regardless of recency',()=>{
 const s=new SessionStore();s.accept(event('code','working',now),now);s.accept({...event('think','thinking',now+5),provider:'claude'},now+5);assert.equal(s.snapshot(now+6).state,'working');assert.equal(s.snapshot(now+6).focus.session,'code');s.accept(event('done','done',now+7),now+7);assert.equal(s.snapshot(now+8).state,'done');assert.equal(s.snapshot(now+8000).state,'working');s.accept(event('code','idle',now+8001),now+8001);assert.equal(s.snapshot(now+8002).state,'thinking');s.accept({...event('think','waiting',now+8003),provider:'claude'},now+8003);assert.equal(s.snapshot(now+8004).state,'idle');assert.ok(s.snapshot(now+8004).conversations.some(e=>e.state==='waiting'));
});
test('individual bubbles and project groups survive another completion being dismissed',()=>{
 const s=new SessionStore();s.accept({...event('one','thinking'),cwd:'/a/shared'},now);s.accept({...event('two','working',now+1),provider:'claude',cwd:'/a/shared'},now+1);s.accept({...event('three','working',now+2),cwd:'/b/shared'},now+2);assert.equal(s.snapshot(now+3).conversations.length,3);assert.deepEqual(s.snapshot(now+3).projects.map(p=>p.count),[2,1]);s.accept({...event('one','done',now+4),cwd:'/a/shared'},now+4);s.accept({...event('two','done',now+5),provider:'claude',cwd:'/a/shared'},now+5);assert.equal(s.snapshot(now+9000).conversations.filter(e=>e.state==='done').length,2);assert.equal(s.acknowledge('codex:one',now),false);assert.equal(s.acknowledge('codex:one',now+4),true);assert.equal(s.snapshot(now+9000).projects[0].count,1);assert.equal(s.acknowledge('claude:two',now+5),true);assert.equal(s.snapshot(now+9000).projects.length,1);assert.equal(s.snapshot(now+9000).conversations[0].session,'three');
});
test('dismissed completions stay closed after replay, and a new turn creates its own bubble',()=>{
 const s=new SessionStore();s.accept(event('one','done'),now);s.acknowledge('codex:one',now);const restarted=new SessionStore([...s.dismissed]);restarted.accept(event('one','done'),now);assert.equal(restarted.snapshot(now).conversations.length,0);restarted.accept(event('one','thinking',now+1),now+1);assert.equal(restarted.snapshot(now+2).conversations[0].state,'thinking');assert.equal(restarted.acknowledge('codex:one',now),false);restarted.accept(event('one','done',now+3),now+3);assert.equal(restarted.snapshot(now+4).conversations[0].state,'done');
});
test('lists have bounded height and remain inside smaller displays',()=>{const {petLayout}=require('../src/pet-layout.cjs');assert.equal(petLayout(0,0).height,240);assert.equal(petLayout(2,1).topHeight,116);assert.equal(petLayout(100,100).height,520);assert.ok(petLayout(100,100,500).height<=500);});
test('provider snapshots isolate conversations, projects, and animation priorities',()=>{const s=new SessionStore();s.accept(event('codex','working'),now);s.accept({...event('claude','thinking',now+1),provider:'claude'},now+1);s.accept({...event('finished','done',now+2),provider:'copilot'},now+2);assert.equal(s.snapshot(now+3).state,'done');assert.equal(s.snapshot(now+3,'codex').state,'working');assert.equal(s.snapshot(now+3,'claude').state,'thinking');assert.equal(s.snapshot(now+3,'claude').conversations.length,1);assert.equal(s.snapshot(now+3,'claude').projects[0].count,1);assert.equal(s.snapshot(now+3,'idle').conversations.length,0);});

test('assigned pets can stay visible at rest without inventing activity or a conversation',()=>{const {visibleProviders}=require('../src/companions.cjs');const selection={mode:'per-tool',assignments:{claude:'toktok'}};assert.deepEqual(visibleProviders([],selection),['claude']);assert.deepEqual(visibleProviders([],selection,false),['idle']);assert.deepEqual(visibleProviders([{provider:'codex'}],selection),['codex','claude']);assert.deepEqual(visibleProviders([],{...selection,mode:'shared'}),['idle']);const s=new SessionStore().snapshot(Date.now(),'claude');assert.equal(s.state,'idle');assert.equal(s.conversations.length,0);assert.equal(s.projects.length,0);});


test('scaled layouts fit small displays and preferences remain independent',()=>{
 const {petLayout,petPreference}=require('../src/pet-layout.cjs');
 for(const scale of [.6,1,1.5])for(const height of [300,500,900]){const l=petLayout(100,1,height,scale,400);assert.ok(l.height<=height);assert.ok(l.width<=400);assert.ok((240+l.topHeight+l.bottomHeight)*l.scale<=l.height);}
 const settings={petAppearance:{claude:{scale:.8,hidden:true},codex:{scale:1.4}}};
 assert.deepEqual(petPreference(settings,'claude'),{scale:.8,hidden:true});assert.deepEqual(petPreference(settings,'codex'),{scale:1.4,hidden:false});assert.deepEqual(petPreference(settings,'idle'),{scale:1,hidden:false});
 assert.deepEqual(petPreference({petAppearance:{codex:{scale:'wrong',hidden:1}}},'codex'),{scale:1,hidden:false});
});
