'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events');
const {UpdateManager,newerVersion,RELEASES_URL}=require('../src/updates.cjs');
function fixture(extra={}){const updater=new EventEmitter(),calls=[];updater.checkForUpdates=async()=>{calls.push('check');updater.emit('update-not-available');};updater.quitAndInstall=(...args)=>calls.push(['install',...args]);const manager=new UpdateManager({version:'0.7.0',packaged:true,platform:'win32',updater,fetchRelease:async()=>({tag_name:'v0.8.0'}),openExternal:async url=>calls.push(url),beforeInstall:()=>calls.push('quitting'),...extra});return {manager,updater,calls};}
test('stable versions compare numerically and reject downgrades and prereleases',()=>{assert.ok(newerVersion('v0.10.0','0.9.0'));for(const v of ['v0.7.0','v0.6.9','0.8.0-beta.1','bad'])assert.equal(newerVersion(v,'0.7.0'),false);});
test('updates download automatically but never install on quit or before ready',async()=>{const {manager,updater,calls}=fixture();assert.equal(updater.autoDownload,true);assert.equal(updater.autoInstallOnAppQuit,false);await manager.install();assert.deepEqual(calls,[]);updater.emit('update-available',{version:'0.8.0'});assert.equal(manager.snapshot().status,'downloading');updater.emit('download-progress',{percent:52.3});assert.equal(manager.snapshot().progress,52);await manager.check();assert.deepEqual(calls,[]);updater.emit('update-downloaded',{version:'0.8.0'});await manager.install();assert.deepEqual(calls,['quitting',['install',false,true]]);assert.equal(manager.snapshot().status,'installing');});
test('unsigned Mac offers a fixed release link without invoking native updater',async()=>{const {manager,updater,calls}=fixture({platform:'darwin',fetchRelease:async()=>({tag_name:'v0.8.0',html_url:'https://attacker.invalid'})});assert.equal(manager.automatic,false);assert.equal(updater.listenerCount('error'),0);await manager.check();assert.equal(manager.snapshot().status,'manual');await manager.install();assert.deepEqual(calls,[RELEASES_URL]);});
test('signed Mac supports the native update flow',()=>{const {manager}=fixture({platform:'darwin',macSigned:true});assert.equal(manager.automatic,true);});
test('development never makes update requests',async()=>{const {manager,calls}=fixture({packaged:false});await manager.check();await manager.install();manager.start();assert.equal(manager.snapshot().status,'development');assert.deepEqual(calls,[]);assert.equal(manager.initial,undefined);});
test('manual update checks ignore draft, prerelease, missing and older releases',async()=>{for(const release of [null,{tag_name:'v0.8.0',draft:true},{tag_name:'v0.8.0',prerelease:true},{tag_name:'v0.6.0'}]){const {manager}=fixture({platform:'darwin',fetchRelease:async()=>release});await manager.check();assert.equal(manager.snapshot().status,'current');}});
test('errors stay recoverable and simultaneous checks are coalesced',async()=>{let fail=true,resolve;const {manager,updater,calls}=fixture();updater.checkForUpdates=async()=>{calls.push('check');await new Promise(r=>resolve=r);if(fail)throw Error('private transport details');updater.emit('update-not-available');};const pending=manager.check();await manager.check();assert.deepEqual(calls,['check']);resolve();await pending;assert.equal(manager.snapshot().status,'error');assert.ok(!JSON.stringify(manager.snapshot()).includes('private'));fail=false;const retry=manager.check();resolve();await retry;assert.equal(manager.snapshot().status,'current');});
