const {_electron:electron}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'agentibou-ui-')),events=path.join(root,'events'),qa=path.resolve('docs/qa');fs.mkdirSync(events);fs.mkdirSync(qa,{recursive:true});let app,clock=Date.now();const errors=[];
 const env={...process.env,AGENTIBOU_HOME:root,CODEX_HOME:path.join(root,'none'),AGENTIBOU_CLAUDE_DESKTOP_HOME:path.join(root,'claude-desktop')};
 const launch=async()=>{app=await electron.launch({args:[path.resolve('.')],env});app.on('window',w=>w.on('pageerror',e=>errors.push(e.message)));for(const w of app.windows())w.on('pageerror',e=>errors.push(e.message));};
 const page=async(provider)=>{for(let i=0;i<100;i++){const p=app.windows().find(w=>!w.isClosed()&&(provider?new URL(w.url()||'about:blank').searchParams.get('provider')===provider:w.url().endsWith('index.html')));if(p){await p.waitForFunction(()=>!!window.agentibou);return p;}await new Promise(r=>setTimeout(r,100));}throw Error('Missing window '+provider);};
 const write=(file,e)=>{clock=Math.max(Date.now(),clock+1);fs.writeFileSync(path.join(events,file+'.json'),JSON.stringify({...e,at:clock}));return clock;};
 const row=(p,provider,id)=>p.locator(`.conversation[data-key="${provider}:${id}"]`);
 const state=async(p,value)=>p.waitForFunction(v=>document.querySelector('.sprite').getAttribute('aria-label').includes(v),value);
 const count=async(p,n)=>p.waitForFunction(n=>document.querySelectorAll('.conversation').length===n,n);
 try{
  await launch();let dashboard=await page(),idle=await page('idle');
  assert.match(await dashboard.title(),/^Agentibou/);
  assert.equal(await dashboard.locator('.brand').innerText().then(s=>s.includes('Agentibou')),true);
  for(const [s,description] of [['idle','repos'],['thinking','réflexion'],['working','travail'],['done','célèbre']]){await dashboard.locator(`[data-demo="${s}"]`).click();await state(idle,description);await idle.screenshot({path:path.join(qa,'pet-'+s+'.png')});if(s==='working'){const a=await idle.locator('.sprite').evaluate(e=>e.style.backgroundPosition);await new Promise(r=>setTimeout(r,200));assert.notEqual(await idle.locator('.sprite').evaluate(e=>e.style.backgroundPosition),a);}}
  await dashboard.locator('#motion-mode').selectOption('reduced');await dashboard.locator('[data-demo="thinking"]').click();await state(idle,'réflexion');const first=await idle.locator('.sprite').evaluate(e=>e.style.backgroundPosition);await new Promise(r=>setTimeout(r,350));assert.equal(await idle.locator('.sprite').evaluate(e=>e.style.backgroundPosition),first);await dashboard.locator('#motion-mode').selectOption('full');await dashboard.locator('#end-demo').click();
  await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},path.resolve('src/assets/vic.webp'));
  await dashboard.locator('#new-companion-name').fill('Pixel');await dashboard.locator('#import-companion button').click();await dashboard.waitForFunction(()=>document.querySelectorAll('.companion-card').length===3);
  const imported=(await dashboard.evaluate(()=>window.agentibou.getState())).companions.find(p=>p.name==='Pixel');assert.ok(imported);
  await dashboard.locator('#shared-companion').uncheck();await dashboard.locator('[data-provider="claude"]').selectOption(imported.id);await dashboard.waitForFunction(async id=>(await window.agentibou.getState()).companionSelection.assignments.claude===id,imported.id);
  await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},path.join(qa,'pet-idle.png'));assert.match((await dashboard.evaluate(()=>window.agentibou.importCompanion('Invalid'))).error,/1536/);
  const restingClaude=await page('claude');await count(restingClaude,0);await state(restingClaude,'repos');assert.equal(await restingClaude.locator('.sprite').getAttribute('data-companion-id'),imported.id);assert.equal(await restingClaude.locator('#idle-status').isVisible(),true);
  await dashboard.locator('#keep-assigned-visible').uncheck();await restingClaude.waitForEvent('close');
  const id='01a09630-c63a-7cb2-b36a-42be68437b18',claudeId='12345678-1234-1234-1234-123456789abc';
  const c={provider:'codex',session:id,project:'Projet partagé',cwd:'/tmp/shared'},c2={provider:'codex',session:'secondary',project:'Projet partagé',cwd:'/tmp/shared'},c3={provider:'codex',session:'third',project:'Autre projet',cwd:'/tmp/other'},cl={provider:'claude',session:claudeId,project:'Projet Claude',cwd:'/tmp/claude'};
  write('code',{...c,state:'working'});write('secondary',{...c2,state:'thinking'});write('third',{...c3,state:'thinking'});write('claude',{...cl,state:'thinking'});
  let codex=await page('codex'),claude=await page('claude');await count(codex,3);await count(claude,1);await state(codex,'travail');await state(claude,'réflexion');
  assert.equal(await codex.locator('.sprite').getAttribute('data-companion-id'),'vic');assert.equal(await claude.locator('.sprite').getAttribute('data-companion-id'),imported.id);
  assert.equal(await claude.evaluate(async()=>{const img=new Image();img.src=JSON.parse(document.querySelector('.sprite').style.backgroundImage.slice(4,-1));await img.decode();return img.naturalWidth;}),1536);
  assert.equal(await codex.locator('.project').count(),0);assert.equal(await claude.locator('.project').count(),0);assert.equal(await codex.locator('#usage').isVisible(),false);assert.equal(await codex.locator('.conversation-open:enabled').count(),0);
  // Different tools have distinct windows and independent state/companion selection.
  const bounds=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().filter(w=>w.webContents.getURL().includes('pet.html?provider=')).map(w=>w.getBounds()));assert.equal(bounds.length,2);assert.notEqual(bounds[0].x,bounds[1].x);
  // Individual controls resize the full widget without changing its neighbour.
  const nativePet=provider=>app.evaluate(({BrowserWindow},provider)=>{const w=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('provider='+provider));return {visible:w.isVisible(),bounds:w.getBounds()};},provider);
  const sizeRow=provider=>dashboard.locator(`[data-pet-provider="${provider}"]`);
  const setSize=async(provider,value)=>{const range=sizeRow(provider).locator('input');await range.fill(String(value));await range.dispatchEvent('change');};
  await codex.locator('#pet-character').hover();await codex.locator('#grow-pet').click();await codex.waitForFunction(()=>Math.round(document.querySelector('.pet-shell').getBoundingClientRect().width)===330);
  assert.equal((await nativePet('codex')).bounds.width,330);assert.equal((await nativePet('claude')).bounds.width,300);
  await setSize('claude',60);await claude.waitForFunction(()=>Math.round(document.querySelector('.pet-shell').getBoundingClientRect().width)===180);assert.equal((await nativePet('claude')).bounds.width,180);
  await claude.locator('#pet-character').hover();await claude.locator('#hide-pet').click();assert.equal((await nativePet('claude')).visible,false);assert.equal((await nativePet('codex')).visible,true);
  await dashboard.locator('#toggle-pet').click();await dashboard.locator('#toggle-pet').click();assert.equal((await nativePet('claude')).visible,false);assert.equal((await nativePet('codex')).visible,true);
  write('claude',{...cl,state:'idle'});await claude.waitForEvent('close');write('claude',{...cl,state:'working'});claude=await page('claude');await state(claude,'travail');assert.equal((await nativePet('claude')).visible,false);assert.equal((await nativePet('claude')).bounds.width,180);await count(claude,1);
  assert.ok((await codex.evaluate(()=>window.agentibou.petAppearance('claude',{hidden:false}))).error);assert.ok((await dashboard.evaluate(()=>window.agentibou.petAppearance('codex',{scale:NaN}))).error);
  await sizeRow('claude').getByRole('button',{name:'Réafficher · Claude Code',exact:true}).click();assert.equal((await nativePet('claude')).visible,true);
  await setSize('codex',100);await setSize('claude',100);write('claude',{...cl,state:'thinking'});await state(claude,'réflexion');
  await dashboard.locator('#shared-companion').check();await claude.waitForFunction(()=>document.querySelector('.sprite').dataset.companionId==='vic');await dashboard.locator('#shared-companion').uncheck();await claude.waitForFunction(id=>document.querySelector('.sprite').dataset.companionId===id,imported.id);
  await app.evaluate(({shell})=>{globalThis.__opened=[];shell.openExternal=async uri=>globalThis.__opened.push(uri);});
  write('third',{...c3,state:'done'});await state(codex,'célèbre');await state(claude,'réflexion');await codex.screenshot({path:path.join(qa,'multi-conversations.png')});await claude.screenshot({path:path.join(qa,'claude-companion.png')});
  await dashboard.locator('[data-demo="thinking"]').click();assert.equal(await row(codex,'codex','third').locator('.conversation-open').isEnabled(),false);assert.equal(await row(codex,'codex','third').locator('.conversation-dismiss').isEnabled(),false);await dashboard.locator('#end-demo').click();
  await state(codex,'travail');assert.equal(await row(codex,'codex','third').locator('.conversation-open').isEnabled(),true);
  await row(codex,'codex','third').locator('.conversation-dismiss').click();await count(codex,2);assert.equal(await codex.locator('.project').count(),0);assert.deepEqual(await app.evaluate(()=>globalThis.__opened),[]);
  write('code',{...c,state:'done'});await row(codex,'codex',id).locator('.conversation-dismiss').waitFor();
  const box=await codex.locator('#pet-character').boundingBox();await codex.mouse.move(box.x+96,box.y+100);await codex.mouse.down();await codex.mouse.move(box.x+110,box.y+103,{steps:4});await codex.mouse.up();await codex.locator('#pet-character').click();assert.deepEqual(await app.evaluate(()=>globalThis.__opened),[]);
  await row(codex,'codex',id).locator('.conversation-open').click();await count(codex,1);assert.equal(await codex.locator('.project').count(),0);assert.deepEqual(await app.evaluate(()=>globalThis.__opened),['codex://threads/'+id]);
  const desktopId='local_12345678-1234-1234-1234-123456789abc',meta=path.join(root,'claude-desktop','claude-code-sessions','account','org');fs.mkdirSync(meta,{recursive:true});fs.writeFileSync(path.join(meta,desktopId+'.json'),JSON.stringify({sessionId:desktopId,cliSessionId:claudeId}));write('claude',{...cl,state:'done'});await row(claude,'claude',claudeId).locator('.conversation-dismiss').waitFor();await row(claude,'claude',claudeId).locator('.conversation-open').click();await claude.waitForEvent('close');assert.deepEqual(await app.evaluate(()=>globalThis.__opened),['codex://threads/'+id,'claude://claude.ai/claude-code-desktop/'+desktopId]);
  // Failed navigation preserves only that bubble and × still works.
  await app.evaluate(({shell})=>{shell.openExternal=async()=>{throw Error('No handler');};});write('code',{...c,state:'done'});await row(codex,'codex',id).locator('.conversation-dismiss').waitFor();await row(codex,'codex',id).locator('.conversation-open').click();assert.equal(await row(codex,'codex',id).count(),1);await row(codex,'codex',id).locator('.conversation-dismiss').click();await count(codex,1);
  // New activity restores Claude's own companion, including while all pets are hidden.
  await dashboard.locator('#toggle-pet').click();write('claude',{...cl,state:'thinking'});claude=await page('claude');await count(claude,1);await new Promise(r=>setTimeout(r,200));assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().filter(w=>w.webContents.getURL().includes('pet.html?provider=')).every(w=>!w.isVisible())),true);await dashboard.locator('#toggle-pet').click();await state(claude,'réflexion');assert.equal(await claude.locator('.sprite').getAttribute('data-companion-id'),imported.id);
  for(const provider of ['copilot','visualstudio']){write(provider,{provider,session:provider,project:provider,state:'working'});const p=await page(provider);await count(p,1);await state(p,'travail');write(provider,{provider,session:provider,project:provider,state:'idle'});await p.waitForEvent('close');}
  for(let i=0;i<10;i++)write('bulk'+i,{provider:'codex',session:'bulk'+i,project:'Projet '+i,cwd:'/tmp/project'+i,state:'thinking'});await count(codex,11);assert.equal(await codex.locator('#conversations').evaluate(e=>e.scrollHeight>e.clientHeight),true);assert.equal(await codex.locator('#projects').count(),0);await codex.locator('.conversation').last().scrollIntoViewIfNeeded();await codex.screenshot({path:path.join(qa,'many-conversations.png')});assert.equal(await codex.evaluate(()=>document.documentElement.scrollHeight>innerHeight),false);
  await dashboard.locator('#keep-assigned-visible').check();write('claude',{...cl,state:'idle'});await count(claude,0);await state(claude,'repos');assert.equal(await claude.locator('#idle-status').isVisible(),true);
  // Data comes from real reader paths, never invented for absent providers.
  const day=new Date(),logdir=path.join(root,'none','sessions',String(day.getFullYear()),String(day.getMonth()+1).padStart(2,'0'),String(day.getDate()).padStart(2,'0'));fs.mkdirSync(logdir,{recursive:true});const log=path.join(logdir,'usage.jsonl');const timestamp=new Date().toISOString();const limit={limit_id:'codex',primary:{used_percent:54,window_minutes:10080,resets_at:Math.floor(Date.now()/1000)+86400},secondary:null};fs.writeFileSync(log,[{type:'session_meta',payload:{id:'bulk9',cwd:'/tmp/project9'}},{type:'event_msg',timestamp,payload:{type:'token_count',info:{total_token_usage:{total_tokens:123456}},rate_limits:limit}}].map(JSON.stringify).join('\n')+'\n');
  const claudeRoot=path.join(root,'claude-desktop');fs.mkdirSync(claudeRoot,{recursive:true});fs.writeFileSync(path.join(claudeRoot,'plan-usage-history.json'),JSON.stringify({version:2,samples:[{t:Date.now()-1800000,org:'test',u:{fh:68,sd:18}}]}));
  await codex.waitForFunction(()=>document.querySelector('[data-key="week"].usage-metric')?.textContent==='7 j 54 %',{},{timeout:20000});await claude.waitForFunction(()=>document.querySelector('[data-key="week"].usage-metric')?.textContent==='7 j 18 %',{},{timeout:20000});
  assert.equal(await codex.locator('.usage-metric[data-key="fiveHour"]').count(),0);assert.equal(await codex.locator('.usage-metric[data-key="conversation"]').count(),1);assert.match(await codex.locator('.usage-metric[data-key="conversation"]').textContent(),/tokens/);assert.equal(await claude.locator('.usage-metric.stale').count(),2);assert.match(await claude.locator('#usage-observed').textContent(),/relevé/);
  await codex.screenshot({path:path.join(qa,'codex-usage.png')});await claude.screenshot({path:path.join(qa,'claude-usage.png')});
  // Maximum size still fits the screen with many bubbles; preference survives restart.
  await setSize('codex',150);await codex.waitForFunction(()=>Math.round(document.querySelector('.pet-shell').getBoundingClientRect().width)===450);
  assert.equal(await codex.evaluate(()=>{const r=document.querySelector('.pet-shell').getBoundingClientRect();return r.bottom<=innerHeight+1&&r.right<=innerWidth+1;}),true);
  await codex.locator('#pet-character').hover();assert.equal(await codex.evaluate(()=>{const r=document.querySelector('.pet-shell').getBoundingClientRect();return r.top===0&&r.left===0&&Math.abs(r.bottom-innerHeight)<=1&&scrollY===0;}),true);await codex.screenshot({path:path.join(qa,'pet-resize-controls.png')});
  await setSize('codex',80);await setSize('claude',130);await sizeRow('claude').getByRole('button',{name:'Masquer · Claude Code',exact:true}).click();
  await sizeRow('codex').scrollIntoViewIfNeeded();await dashboard.screenshot({path:path.join(qa,'individual-settings.png')});
  const before=await dashboard.evaluate(()=>window.agentibou.getState());assert.equal(before.companionSelection.assignments.claude,imported.id);assert.deepEqual(errors,[]);
  await app.close();app=null;await launch();dashboard=await page();codex=await page('codex');claude=await page('claude');await count(codex,11);await count(claude,0);assert.equal(await claude.locator('#idle-status').isVisible(),true);assert.equal(await claude.locator('.sprite').getAttribute('data-companion-id'),imported.id);assert.equal(await row(codex,'codex',id).count(),0);assert.equal(await row(codex,'codex','third').count(),0);
  assert.equal((await nativePet('claude')).visible,false);assert.equal((await nativePet('codex')).visible,true);assert.equal((await nativePet('codex')).bounds.width,240);assert.equal((await nativePet('claude')).bounds.width,390);
  await sizeRow('claude').getByRole('button',{name:'Réafficher · Claude Code',exact:true}).click();assert.equal((await nativePet('claude')).visible,true);
  assert.equal(await dashboard.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  console.log('UI OK: independent resize/hide controls, screen fit, recovery and persistence; separate windows per tool; different companions; isolated conversations/projects; priorities; exact native links; close/open acknowledgements; persistent dismissal; new turn; hidden-window lifecycle; scrolling; unchanged image import; animation previews and reduced motion.');
 }finally{if(app)await app.close();fs.rmSync(root,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
